language: php

php:
  - hhvm
  - 5.5
  - 5.6

sudo: false

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --prefer-dist --no-interaction
  
# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

script:
  - vendor/bin/phpunit --verbose
